enum TokenType
{
    LEFT_PAREN, RIGHT_PAREN,
    LEFT_BRACE, RIGHT_BRACE,
    COMMA, DOT,
    MINUS, PLUS,
    SLASH, STAR,
    BANG, BANG_EQUAL,
    EQUAL, EQUAL_EQUAL,
    GREATER, GREATER_EQUAL,
    LESS, LESS_EQUAL,
    IDENTIFIER, STRING, NUMBER,
    AND, OR,
    PRINT, FOR, WHILE,
    IF, ELSE,
    CLASS, SUPER, THIS,
    FUN, RETURN,
    TRUE, FALSE,
    VAR, NIL, EOF,
    SEMICOLON
}